---
title: "EDA"
author: "Tianqi Li"
date: "2024-10-08"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(readxl)
```


```{r}
weather_df <- 
  read_csv("weather_df.csv", na = c("NA", "", ".")) |>  
  janitor::clean_names() |>
  mutate(month = floor_date(date, unit = "month"))
```

```{r}
weather_df |>
  ggplot(aes(x = prcp)) + geom_histogram()
```

```{r}
weather_df |>
  filter(prcp > 1000)
```

```{r}
weather_df |>
  filter(tmax > 20, tmax <30) |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point()
```

## group_by()
```{r}
weather_df |>
  group_by(name,month)
```

counting stuff
```{r}
weather_df |>
  group_by(name) |>
  summarize(n_obs = n(),
            n_dist = n_distinct(month))
```

```{r}
weather_df |>
  group_by(name,month) |>
  summarize(n_obs = n())
```

```{r}
weather_df |>
  count(name)
```

## 2x2
```{r}
weather_df |>
  drop_na(tmax) |>
  filter(name != "Molokai_HI") |>
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold"
    )
  ) |>
  group_by(name, cold) |>
  summarise(count = n())
```

```{r}
weather_df |>
  drop_na(tmax) |>
  filter(name != "Molokai_HI") |>
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold"
    )
  ) |>
  janitor::tabyl(name,cold)
```


## general numeric summaries

